name: My Fisrt Workflow

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:

  build:
    name: Main testing
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install donet SDK
      uses: action/setup-dotnet@v3
      with:
        dotnet-version: '6.0'

    - name: Build project
      run: dotnet build
    
    
    

